dist: bionic
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - g++-7
            - binutils
            - python3-setuptools
            - python3-pip
            - openjdk-11-jre
            - build-essential
            - eclipse-cdt
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

compiler:
- gcc

before_install:
- eval "${MATRIX_EVAL}"

install:
- sudo pip3 install --upgrade pip
- pip install --user six==1.12 cpp-coveralls conan
- conan remote add CynaraKrewe https://api.bintray.com/conan/cynarakrewe/CynaraConan
- conan remote remove conan-center
- conan install .
- cd ..

script:
- eclipse --launcher.suppressErrors -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -data temp -import Flow -cleanBuild "Flow/Release"
- ./Flow/Release/Flow

after_success:
- eclipse --launcher.suppressErrors -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -data temp -import Flow -cleanBuild "Flow/Debug"
- cd Flow/Debug/
- ./Flow
- gcov-5 `find . -name *.o`
- cd ../
- coveralls -n -b Debug/ -e include/CppUTest -e include/CppUTestExt/
