dist: trusty
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5

compiler:
- gcc

install:
- sudo pip install conan
- conan remote add CynaraKrewe https://api.bintray.com/conan/cynarakrewe/CynaraConan
- sudo apt-get install -qq build-essential eclipse-cdt

script:
- cd ..
- conan install Flow
- eclipse --launcher.suppressErrors -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -data temp -import Flow -cleanBuild "Flow/Release"
