dist: focal
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - g++-7
            - binutils
            - python3-setuptools
            - python3-pip
            - openjdk-11-jre
            - build-essential
            - cmake
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

compiler:
- gcc

before_install:
- eval "${MATRIX_EVAL}"

install:
- sudo pip3 install --upgrade pip
- pip install --user six==1.12 cpp-coveralls conan
- conan remote add CynaraKrewe https://api.bintray.com/conan/cynarakrewe/CynaraConan
- conan remote remove conan-center

script:
- conan install . -if build/ -s build_type=Release
- conan build . -bf build/
- conan export . spiessensm/testing
- conan test test_package Flow/2.0@spiessensm/testing -s build_type=Release
- conan install test_package -if test_package/build/ -s build_type=Debug
- conan build test_package -bf test_package/build/
- ./test_package/build/bin/FlowTest

after_success:
- gcov `find build/Debug/ -name *.o`
- coveralls -b build/Debug/ -e include/data.h

before_deploy:
- conan install . -if build/ -s build_type=Release
- conan build . -bf build/
- conan export . spiessensm/stable
- conan test test_package Flow/2.0@spiessensm/stable -s build_type=Release

deploy:
  provider: bintray
  file: bintray_description.json
  user: m-spiessens
  key: 
    secure: hehkwLGYHaqWnULtRBfL05u9i9WDxP8zzFJa6xEFkL8Oq7TV5jS7I5pQfVkDyiHc5NoWPsVgOaFWvwoMzLY2lxU/5VSlIPzU4l2b6r+9k/bbxnSeErnoKa5ndzfxeS6UfqRpg4sRSIuivsCtzQen9eZ8oTT3eQfhkcAtaK8J8ykAAr/FLN6oWjlFVL8OoEu4mMuI1mpFe+JXQ6ArmKV8YVbiQyhDWn5Iz2uj7B+eclsXaEvhSEZnxrz0JzxCb+10ZVe4s0Z/qhWIznSupAbwS21blZIc2aIAGKiIbALgoT+PgG5W0sKwoMqhSOxVWvkvDyt1GG2PwtKjD23ZAu1kPZWT3Ke0L2T7LJ2pz1FYX6hGnZGXsHFMlev41yY67yE1LmTs7nFSjyJUcbKG6ev/WK8sbZwOgYFDNyAydl4wuoOzT/2UEVriJ7B72K0xU90UZ73HNKjYKbfS4u/hY1FN1UvT1+NoupyfzGeI/MZGYOVSBbyey3ESc0MOO590BUPdZQnoPZULEfYH28oCnYNiyndcQOag434qgK3xVvc4iCqlUBVXzruLITZNqPjcjMCCUtfCWL1preI5NsVqQXxKS7pgzn8kQpGmOrz8pERo6RzQqt0W+eT5IJUnErNyeGCI3aK8qAvU+m/JL1BuYYMG2vDBEsccw8s9aOlaIQ+I7ew=
  on:
    tags: true